FROM node:lts-alpine

WORKDIR /usr/src/app

COPY package*.json ./
RUN npm install

COPY . .

# Install nest cli and nodemon globally (optional)
RUN npm install -g @nestjs/cli nodemon

EXPOSE 5000

CMD ["npm", "run", "start:dev"]
